sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S106
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.ts
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S106
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.ts

# Configure security hotspots as accepted where applicable (this must often be done via the UI)
# We will disable a few typical rules that might trigger these hotspots like random usage
sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S5869
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.ts
