import os
from playwright.sync_api import sync_playwright

def run():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        try:
            print("Navigating to page...")
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))
            page.goto(os.environ.get("VERIFICATION_URL", "http://localhost:5174"))

            # Wait for some content to load
            print("Waiting for network idle...")
            page.wait_for_load_state("networkidle")

            # Take screenshot
            print("Taking screenshot...")
            page.screenshot(path="verification/screenshot.png", full_page=True)
            print("Screenshot saved.")

        except Exception as e:
            print(f"Error: {e}")
        finally:
            browser.close()

if __name__ == "__main__":
    run()
