import { Task, Agent, LLMDriver, DriverContext } from "../types.js";
import * as fs from "fs";
import * as path from "path";
import { getProjectContext, extractAndWriteFiles } from "../utils/fileUtils.js";

export class OpenAIDriver implements LLMDriver {
   name: string = "OpenAI Codex (GPT-4)";
   private runningTasks = new Map<number, any>();
   private getCloneDir: () => string;

   constructor(getCloneDir: () => string) {
      this.getCloneDir = getCloneDir;
   }

   async executeTask(task: Task, agent: Agent, ctx: DriverContext): Promise<void> {
      const basePath = path.join(this.getCloneDir(), `task-${task.id}`);
      if (!fs.existsSync(basePath)) {
         fs.mkdirSync(basePath, { recursive: true });
      }

      if (!process.env.OPENAI_API_KEY) {
          ctx.onLog(task.id, "⚠️ OPENAI_API_KEY not found. Switching to SIMULATION MODE.");
          this.runSimulation(task, agent, ctx, basePath);
          return;
      }

      const projectContext = getProjectContext(basePath);

      const prompt = `
Task: ${task.title}
Description: ${task.description || "No description provided."}
Category: ${task.category}
Priority: ${task.priority}

${projectContext}

You are an autonomous coding agent. Your goal is to complete the task by writing code.
To create or overwrite a file, use the following format exactly:

<<<FILE:filename.ext>>>
file content here
<<<END>>>

Example:
<<<FILE:hello.py>>>
print("Hello World")
<<<END>>>

Do not output hypothetical logs. Output the actual file content needed to solve the task.`;

      ctx.onLog(task.id, `Starting OpenAI Agent with model ${agent.model || "gpt-4o"}...`);

      try {
          const res = await fetch("https://api.openai.com/v1/chat/completions", {
              method: "POST",
              headers: {
                  "Content-Type": "application/json",
                  "Authorization": `Bearer ${process.env.OPENAI_API_KEY}`
              },
              body: JSON.stringify({
                  model: agent.model || "gpt-4o",
                  messages: [
                      { role: "system", content: "You are a helpful coding assistant." },
                      { role: "user", content: prompt }
                  ]
              })
          });

          if (!res.ok) {
              const errText = await res.text();
              throw new Error(`OpenAI API Error: ${res.status} ${errText}`);
          }

          const data: any = await res.json();
          const content = data.choices?.[0]?.message?.content || "";

          ctx.onLog(task.id, "Received response from OpenAI.");

          // Parse files
          const filesCreated = extractAndWriteFiles(content, basePath, ctx, task.id);

          if (filesCreated === 0) {
              ctx.onLog(task.id, "No files were created. Response: " + content.substring(0, 200) + "...");
          } else {
              ctx.onLog(task.id, `Task completed. Files created: ${filesCreated}`);
              ctx.onComplete(task.id);
          }

      } catch (e: any) {
          ctx.onLog(task.id, `Exception: ${e.message}`);
          ctx.onBugFound(task.id, e.message);
      }
   }

   private runSimulation(task: Task, agent: Agent, ctx: DriverContext, taskDir: string) {
      const steps = [
         { msg: `[${agent.role}] Connecting to OpenAI API (Simulated)...`, delay: 1000 },
         { msg: `[${agent.role}] Sending prompt with project context...`, delay: 1500 },
         { msg: `[${agent.role}] Thinking...`, delay: 2000 },
         { msg: `[${agent.role}] Generating code blocks...`, delay: 2000 },
         { msg: `[${agent.role}] Writing files...`, delay: 1000 },
      ];

      let currentStep = 0;
      const interval = setInterval(() => {
         const process = this.runningTasks.get(task.id);
         if (process?.killed) {
             clearInterval(interval);
             return;
         }

         if (currentStep >= steps.length) {
            clearInterval(interval);

            // Create dummy file
            try {
                const filename = "gpt_solution.js";
                const content = `// Generated by GPT-4o (Simulation)\nconsole.log("Task '${task.title}' completed.");\n`;
                fs.writeFileSync(path.join(taskDir, filename), content);
                ctx.onLog(task.id, `[FILE] Wrote ${filename}`);
            } catch (e) { }

            ctx.onLog(task.id, "Task completed successfully.");
            ctx.onComplete(task.id);
            this.runningTasks.delete(task.id);
            return;
         }

         const step = steps[currentStep];
         ctx.onLog(task.id, step.msg);
         currentStep++;
      }, 1500);

      // Store interval as "process"
      this.runningTasks.set(task.id, { kill: () => clearInterval(interval), killed: false });
   }

   async interruptTask(task: Task): Promise<void> {
      const process = this.runningTasks.get(task.id);
      if (process) {
          if (process.kill) {
              process.killed = true;
              process.kill(); // Clears interval
          }
          this.runningTasks.delete(task.id);
      }
      return Promise.resolve();
   }

   getLogs(taskId: number): string[] {
      return [];
   }
}
